### ISSUE TITLE
List and jump to lines matching a pattern (using helm-swoop)

### ISSUE THREAD

**Issue by mosic** [BrianHicks/spacemacs-rocks#17] opened 2015-09-06 12:04 UTC
@milosmosic on Twitter

Use `SPC s s` to open [helm-swoop](https://github.com/ShingoFukuyama/helm-swoop) which lists all lines matching your search and lets you easily jump to them.

**Comment by BrianHicks** [comment] 2015-09-08 14:35
Thanks! Is it OK if I use your github profile instead? It'll pull in your name and link to your website if I do. GH pages seems to be down for maintenance at the moment, but check out the most recent post when you can to see what I mean.

**Comment by BrianHicks** [comment] 2015-09-08 15:33
Oops, looks like this was a duplicate of #4. It'll be on the site next Tuesday (2015-09-15). Thanks, though!

**Closed as completed by BrianHicks** 2015-09-08 15:33 UTC
Labels: duplicate, tip
